Run Write-Host "Downloading CRD..."
Downloading CRD...
Installing CRD (Quiet Mode)...
Waiting 45 seconds for installation to finish...
4m 5s
Run # Secret check
  
Searching for remoting_start_host.exe...
✅ Path Found: C:\Program Files (x86)\Google\Chrome Remote Desktop\147.0.7727.3\remoting_start_host.exe
Connecting to Google Servers... Please wait.
[0324/080833.072:INFO:remoting\host\setup\daemon_controller_delegate_win.cc:76] 'C:\ProgramData\Google\Chrome Remote Desktop\host_unprivileged.json' does not exist, skipping read.
[0324/080836.081:ERROR:remoting\host\setup\host_starter_base.cc:280] Failed to exchange the authorization_code due to an OAuth error.
Couldn't start host: OAuth error.
Waiting 60 seconds for GitHub-PC to appear online...
Error: Process completed with exit code 1.
